# Ici on a besoin de démarrer un conteneur server à partir de l'image express-docker et un conteneur mongodb à partir de l'image mongo.

services:
  server:
    build: ./server
    ports: 
      - 5050:5000
    command: npm run dev

    # Ici on va connecter server/src/ de notre machine à /app/src/ du conteneur.
    volumes:
      - ./server/src/:/app/src/

  mongodb:
    image: mongo
    volumes: 
      - ./data:/data/db
  app:
      image: ahamel11/hello-app

  client:
    build: ./client
    command: npm start
    volumes: 
      - ./client/src/:/app/src/
    ports:
      - 8080:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
